### ISSUE TITLE
The linked URLs are incorrect

### ISSUE THREAD

**Issue by roottool** [react-hook-form/documentation#1004]
## Overview

On the "Advanced Usage" page, two linked URLs are wrong.

- "FormContext" in [Connect Form](https://react-hook-form.com/advanced-usage#ConnectForm)
- "FormProvider" in [FormProvider Performance](https://react-hook-form.com/advanced-usage#FormProviderPerformance)

### Expected behavior

Linked URL is `/docs#useFormContext` such as a current link of FormProvider.
https://github.com/react-hook-form/documentation/blob/e7cdd0fb68f61667beaca25a4aab5fea88a59178/src/content/advanced-usage.mdx#L306

### Actual behavior

The current URL(`/docs/useFormContext`) is incorrect.
https://github.com/react-hook-form/documentation/blob/e7cdd0fb68f61667beaca25a4aab5fea88a59178/src/content/advanced-usage.mdx#L272

We receive a 404 response from this URL.
![404 Not Found](https://github.com/react-hook-form/documentation/assets/11808736/502155e0-b913-4433-a313-d8b3fd5926ff)

### Expected behavior

Move to [FormProvider](https://react-hook-form.com/docs/formprovider) in API doc.

### Actual behavior

Move to [useFormContext](https://react-hook-form.com/docs/useformcontext) in API doc.
https://github.com/react-hook-form/documentation/blob/e7cdd0fb68f61667beaca25a4aab5fea88a59178/src/content/advanced-usage.mdx#L306

**Comment by bluebill1049** [comment]
Would you like to send a PR on this?

**Comment by roottool** [comment]
Yes. I will try it this weekend.

**Comment by roottool** [comment]
Thank you for reviewing!
This issue fixed by #1005. Could you close this issue?
