### ISSUE TITLE
issue: In the specified sandbox environment, when the onChange event handler is invoked with undefined as its argument, the Component does not receive the updated value. However, despite this, the form data is successfully updated.

### ISSUE THREAD

**Issue by manishjatiwal** [react-hook-form/documentation#1042]
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/rhf-bug-mfygck?file=%2Fsrc%2FApp.js

### Steps to reproduce

Just open the sandbox, and click on the buttons.
The first component uses `undefined` as the argument to `onChange`, and hence is not working as expected.
The second component used empty string as as the argument to `onChange`, and works beautifully.

### Expected behaviour

After setting the value as `undefined` by calling the `onChange(undefined)`, ComponentOne should get the update value i.e, undefined, instead of default value.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
can you share the link for the page? and which codesandbox

**Comment by manishjatiwal** [comment]
https://codesandbox.io/p/sandbox/rhf-bug-mfygck?file=%2Fsrc%2FApp.js

**Comment by bluebill1049** [comment]
yes that's the one you forked, i want to know the original

**Comment by manishjatiwal** [comment]
@bluebill1049 Why close this? I am uncertain about your request. The issue in question can be readily replicated using the provided code sandbox.
