### ISSUE TITLE
Beekai.com outbound connection on homepage?

### ISSUE THREAD

**Issue by NickWoodward** [react-hook-form/documentation#1062]
Just loading the site sets off mwb
![Screenshot 2024-04-18 015011](https://github.com/react-hook-form/documentation/assets/16296682/5a296af3-6d1c-4f66-938c-43e8a500b258)
not sure if this is expected, but not a great look :)

**Comment by bluebill1049** [comment]
Thanks will report to malware bytes as incorrect result.
