### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kajirikajiri** [react-hook-form/documentation#1075]
Unnecessary }

https://github.com/react-hook-form/documentation/blob/dedd322c40f24b2fffac7b44765cf6a65dce91ba/src/content/docs/useform/seterror.mdx?plain=1#L25
https://github.com/react-hook-form/documentation/blob/dedd322c40f24b2fffac7b44765cf6a65dce91ba/src/data/api.tsx#L1298

**Comment by bluebill1049** [comment]
ty
