### ISSUE TITLE
[V6] Revise all korean translations

### ISSUE THREAD

**Issue by adhrinae** [react-hook-form/documentation#266]
Since the first release of the Korean translated documents, It has been a lot of updates.  
I've managed to translate new documentations whenever @bluebill1049 wrote a new or updated document and mentioned me on commits.

However, I didn't pay attention to the existing Korean documentation which was getting behind from the original(English) because of limited time and my priority.

It's a good time to revise all of the translated documents in Korean since the major update is coming out.

I'm going to work on revising documents while translating V6 documents. So the target branch for revising will be `V6`.

`TODO: make a checklist for pages to be revised`

**Comment by bluebill1049** [comment]
Thanks a lot, @adhrinae we can hold this until v6 doc is released :)  ❤️

**Comment by adhrinae** [comment]
I revised all Korean docs except V5 API docs. Should recheck V5 docs after V6 release. I will create another issue for that.
