### ISSUE TITLE
🌐 We need your help on translation.

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/documentation#320]
<img width="258" alt="Screen Shot 2020-06-28 at 5 01 26 pm" src="https://user-images.githubusercontent.com/10513364/85940653-02e8d100-b961-11ea-8b3d-047b28fe9683.png">

I try to help as many developers as we can around the world.

Could we please get some help with the translation above? We are limited with members to support translation and using google translate sometimes is not that accurate as well. 

small PR and improvements are welcome.

**Comment by dandv** [comment]
We can help developers by translating (I know Romanian for example), but that's giving someone a fish instead of teaching them to fish.

Learning English is the best investment a developer can make.

**Comment by cpprookie** [comment]
I will do some work on chinese version.

**Comment by majid-amiri** [comment]
I'd like to help you with translation into Persian but I'm afraid if there's any support for RTL languages on the website or not. :(

**Comment by bluebill1049** [comment]
> I'd like to help you with translation into Persian but I'm afraid if there's any support for RTL languages on the website or not. :(

Thanks a lot @majid-amiri I don't think we have Persian set up just yet, I am hesitant to introduce more language because it slowly becoming a burden unless someone is dedicated to contributing. Thanks for very much considering to help tho.

**Comment by pmaier983** [comment]
I was actually thinking of refactoring the api code (to start) in such a manner that i18n is not too much of a burden. Ideally we could easily add multiple languages, and if there were no contributions for a specific section it would default to english (or whatever language would be best). May have a PR in the near future, but thumbs up if you support the idea (or thumbs down if u have doubts + reply).

**Comment by bluebill1049** [comment]
> I was actually thinking of refactoring the api code (to start) in such a manner that i18n is not too much of a burden. Ideally we could easily add multiple languages, and if there were no contributions for a specific section it would default to english (or whatever language would be best). May have a PR in the near future, but thumbs up if you support the idea (or thumbs down if u have doubts + reply).

That would be dream come true. ❤️

**Comment by cpprookie** [comment]
> I was actually thinking of refactoring the api code (to start) in such a manner that i18n is not too much of a burden. Ideally we could easily add multiple languages, and if there were no contributions for a specific section it would default to english (or whatever language would be best). May have a PR in the near future, but thumbs up if you support the idea (or thumbs down if u have doubts + reply).

I think we can seprate data and current languange from components' concern. For exmaple wrap `Link` with `LanguageContext` so no need to `translateLink`. In this way, page components will become static ui component, and file directories may look like 
data
|__ api.en.ts
|__ api.zh.ts
|__ advanced.en.ts
|__ ...
pages
|__ api.tsx
|__ advanced.tsx

@pmaier983, please let me know if you need help.

**Comment by zeyuri** [comment]
I'm gonna help with the portuguese translation

**Comment by bluebill1049** [comment]
That's awesome! Thank you @zeyuri.

**Comment by cpprookie** [comment]
Hi, @bluebill1049  i'm kind of puzzle  about term `constraint-based validation  api` during translation . I thought `constraint-based` is repetitive before word `validation`. Do you want to express `more declarative validation api` or something else?

**Comment by bluebill1049** [comment]
@cpprookie what about 基于约束验证?

**Comment by cpprookie** [comment]
> @cpprookie what about 基于约束验证?

better than current version. I decide use **校验** for word **validation**  during translation by following ant-design usage. 
But 基于约束 is a little strange and confusing in chinese(at least for me). Could you give a simple comparison with other libs  for further unstanding？

**Comment by bluebill1049** [comment]
Sounds good to me @cpprookie 👍 

I don't have specific example, but as far as I know, we are the first one introduced field-level validation which aligned with HTML standard.

**Comment by cpprookie** [comment]
I get it! thanks for your patient explanation @bluebill1049 .
