### ISSUE TITLE
setError needs update?

### ISSUE THREAD

**Issue by dandv** [react-hook-form/documentation#325]
1. rc5 removed the multiple error call convention, and the release notes declare that `setError('test', 'test', 'test')` is incorrect, but the example at https://react-hook-form.com/api#setError calls `setError("username", "notMatch", "please choose a different username");`

2. The [release notes for rc5](https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.5) have some typos, setErrror, and missing `'` after `test`.

**Comment by bluebill1049** [comment]
hey @dandv thanks I have updated the release note, the doc is updated and will be release soon as well.

**Comment by bluebill1049** [comment]
<img width="934" alt="Screen Shot 2020-06-29 at 1 04 19 pm" src="https://user-images.githubusercontent.com/10513364/85968676-0df73c00-ba09-11ea-95d4-7e1876ea8a19.png">

**Comment by dandv** [comment]
Thanks! BTW, "MULTIPLE ERROR" should have an `S` at the end

**Comment by bluebill1049** [comment]
oops, good one I will adjust.

**Comment by bluebill1049** [comment]
fixed :)
