### ISSUE TITLE
ErrorMessage multiple errors

### ISSUE THREAD

**Issue by MauriceOppenberger** [react-hook-form/documentation#352]
The Documentation of displaying multiple errors does not seem to work properly when using TypeScript
@ [api#ErrorMessage](https://react-hook-form.com/api#ErrorMessage) 
```
<ErrorMessage errors={errors} name="multipleErrorInput">
        {({ messages }) =>
          messages &&
          Object.entries(messages).map(([type, message]) => (
            <p key={type}>{message}</p>
          ))
        }
      </ErrorMessage>
```

Error: 
Property 'children' does not exist on type 'IntrinsicAttributes & { as?: undefined; errors?: DeepMap<inputFields, FieldError>; name: string; message?: string; render?: (data: { ...; }) => ReactNode; } & Pick<...>

solution: 
following npm packages documentation 
@ [npm/hookform](https://www.npmjs.com/package/@hookform/error-message)
```
<ErrorMessage
        errors={errors}
        name="multipleErrorInput"
        render={({ messages }) =>
          messages &&
          Object.entries(messages).map(([type, message]) => (
            <p key={type}>{message}</p>
          ))
        }
      />
```

**Comment by pmaier983** [comment]
I'll investigate whats going on here, and later today I'll see if I can update the example with some TS code and a CodeSandbox. Thank you for bringing this up!

**Comment by pmaier983** [comment]
Take a look at the CodeSandbox's created in https://github.com/react-hook-form/documentation/pull/354. I believe they provide a working example of TS and ErrorMessage!

**Comment by pmaier983** [comment]
Closing this issue, but feel free to re-open if you have a specific CodeSandbox detailing the error! Thank You!
