### ISSUE TITLE
Controller in v5 docs has examples from v6

### ISSUE THREAD

**Issue by irekrog** [react-hook-form/documentation#370]
https://react-hook-form.com/v5/api#Controller

**Comment by bluebill1049** [comment]
can you give us a bit more detail on this?

**Comment by irekrog** [comment]
@bluebill1049 

I mean Controller example with `render` should be in v5 docs?

![Zrzut ekranu 2020-07-14 o 10 32 41](https://user-images.githubusercontent.com/11172548/87403685-7cb5c700-c5bd-11ea-84bc-3d296ca9dcbf.png)
