### ISSUE TITLE
Bugs in Form Builder

### ISSUE THREAD

**Issue by martinfrancois** [react-hook-form/documentation#371]
There are quite a lot of bugs in the form builder that make it practically unusable, here a few:

- After opening the page, enter `Test` as the name in `Input Creator`, press create. Enter `Test2` as the name and press create. In the generated code it says `<input type="undefined" ` for `Test2`
- After opening the page, enter `Test` as the name in `Input Creator`, press create. Enter `Test2` as the name, check `required` and press create. In the generated code it's missing the `required` flag.
  - There are a lot of bugs around this issue, try clicking on `Edit` on a few of the fields in `Layout` and try to check / uncheck `required`, it has no effect on the generated code.
  - Also trying to add any other validations apart from `required`, be it pattern etc., will also not result in any changes. When editing again, changes disappear
  - Also, changing the type after editing has no effect.
- After opening the page, enter `Test` as the name in `Input Creator`, press create. Enter `Test2` as the name and change type to `Select`, no field with the title `Options:` appears. When opening the page and changing the type to `Select` straight up, it does provide `Options:`
- Next to any field in `Layout`, press `Edit`, then press `Delete All`, then confirm the dialog. Input Creator still shows the values from before and when clicking on update, the whole page vanishes, only the blue background can be seen.
- When clicking on "Edit" on one of the elements, `Show Validation` is unchecked, but for example for `First name` it shows the validation parts (min, max, etc.) anyways
- After opening the page, enter `Test` as the name in `Input Creator`, check `Show validation`, then set `max` to `10`, then press create. Now the validation pane is still open. If you now enter `Test2` as the name in `Input Creator` and check `Show validation`, it collapses.
- After having issues like the ones above one can only really clear the cookies and local storage to reset the state back to where it was initially, here it would be great to have like a `Reset` button which resets everything to the fields there were before.

**Comment by pmaier983** [comment]
Thank you so much for bringing these bugs up! We are currently focusing our efforts on improving the more core area's of the doc's, but I'll speak with bill about the form builder. For now I'll archive this issue and then re-open it when we get around to fixing the Form Builder. If you want to open a PR to fix these issue's I would love to review it!
