### ISSUE TITLE
Wrong menu item underlined

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/documentation#375]
Go to: https://react-hook-form.com/api/#useWatch
`useFieldArray` menu item is underlined instead of `useWatch`

<img width="349" alt="image" src="https://user-images.githubusercontent.com/7423207/87554036-e87a5b80-c6b3-11ea-939f-dc3abc118bd8.png">

Go to: https://react-hook-form.com/api#useFieldArray
`useWatch` menu item is underlined instead of `useFieldArray`

<img width="341" alt="image" src="https://user-images.githubusercontent.com/7423207/87554118-05169380-c6b4-11ea-8c16-9abfa88ed935.png">

**Comment by bluebill1049** [comment]
thanks @michalbundyra

**Comment by pmaier983** [comment]
you taking care of this one [Mr.Bill](@bluebill1049)?

**Comment by bluebill1049** [comment]
could you take a look at this one? @pmaier983 it's not trivial

**Comment by pmaier983** [comment]
The following PR fixes the issue: https://github.com/react-hook-form/documentation/pull/376
