### ISSUE TITLE
Deprecated documentation about FieldArrays in Advanced page

### ISSUE THREAD

**Issue by jljouannic** [react-hook-form/documentation#377]
I was misled by the documentation about FieldArrays on the Advanced page:

- This [paragraph](https://github.com/react-hook-form/documentation/blob/master/src/data/en/advanced.tsx#L295-L307) seems misleading as, `append`, `prepend` and so on are supported by the `useFieldArray` hook when used with `Controller`. The [CodeSandbox link](https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-gvgg4) in this paragraph leads to an example which may be considered deprecated, what do you think?
- When I read this [comment](https://github.com/react-hook-form/documentation/blob/0b321d53d83311d5d04b6bcf0f8d48744c3437ad/src/components/codeExamples/useFieldArray.ts#L18) in the code sample below the previous paragraph, I thought I could not use `useFieldArray` with `Controller`. It is only when I clicked the [CodeSandbox link](https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv) in the upper right corner that I realised it was supported. Maybe the embedded code sample should be replaced by the CodeSandbox one to make things clear.

**Comment by pmaier983** [comment]
Awesome recommendations. The v5 -> v6 was a flurry so some of these CodeSandbox's are old. Thank you!

**Comment by pmaier983** [comment]
This Issue was fixed by PR #382.

**Comment by bluebill1049** [comment]
Thanks @pmaier983
