### ISSUE TITLE
Resolver on v6

### ISSUE THREAD

**Issue by Satyam** [react-hook-form/documentation#383]
Sorry to trouble you guys but I pressed the Edit button on the documentation page but it took me to something I didn't understand.  It had references to `validationResolver` instead of plain `resolver` and it didn't contain the heading. So I didn't know what to do so, here I am.

1 The signature of the function in the heading. Once https://github.com/react-hook-form/react-hook-form/pull/2305 is published, the `resolver` function might better be described as:
```js
(values: any, context?: object) => Promise<ResolverReturn> | ResolverReturn
// where:
type ResolverReturn = {values: Record<string, any>, errors: Record<string, string>}
```
2 About custom resolvers, I suggest to add the purpose of the function which actually is not limited to validation but also casting or otherwise transforming the values, adding 

> The purpose of the `resolver` is both to validate the values entered and to transform them before submitting them.
> It receives the values as taken from the input elements and the `context` set when `useForm` was called.
> It should return an object with `values` and `errors` objects, or a Promise that produces such object.
> The property names of both `values` and `errors`  should match the `name` properties of the input elements.

3 It says that the default value of both `values` and `errors` should be `{}`.  Actually, this is wrong.
> The default value of `errors` should be an empty object `{}`
> The default value of `values` should be the same `values` received as a parameter.

4 It doesn't say what to return otherwise:
> If an error is found in a value, the `errors` object should contain a property with the name of the field in error and an error message.
> If no errors are found, `values` might return a modified version of the `values` received as parameters with the property values changed, for example:
```js
return {
   errors: {},
   values: {
      ...values,
      age: parseInt(values.age, 10),
   }
}
```

In my app I haven't dealt with nested properties or field arrays so my description above is probably incomplete for lack of experience in those areas.

**Comment by Satyam** [comment]
I also noticed `resolver` receives a third, undocumented parameter `isValidateAllFieldCriteria`, declared in the [types](https://github.com/react-hook-form/react-hook-form/blob/master/src/types/form.ts#L87) as boolean

**Comment by pmaier983** [comment]
These Look like awesome suggestions, I'm a bit stuck for time right now but ill try to go through them 1 by 1 this weekend. Thank you!

**Comment by bluebill1049** [comment]
Thanks @Satyam `isValidateAllFieldCriteria` and `context` will be injected through `useForm`, that's why it's not documented.

**Comment by Satyam** [comment]
@bluebill1049 : I mention where `context` comes from in item 2 in my list of suggestions in my first comment.  I don't see where `isValidateAllFieldCriteria`, at least no documented place.  
Getting started guides are not meant to be exhaustive, API docs should.

**Comment by pmaier983** [comment]
So after a lot of thought (sorry for the long wait): We are going to prioritize user facing changes for the docs. Most of these details concern the inner workings of RHF, and at this time we are prioritizing overall doc improvements versus contributor improvements. Thank you for pointing this out though! I will definitely keep this issue in mind if we eventually shift focus to contributor doc experience.
