### ISSUE TITLE
🌐 Increase the visibility of the language selector

### ISSUE THREAD

**Issue by adhrinae** [react-hook-form/documentation#403]
As a current state, Some of the busy users don't recognize there might be translated documents for their mother tongue.

I've already got feedback from other Korean developers they didn't even know there is a Korean version of the documentation.

I don't want to complain about the design of our documentation, however, I believe that there is a way to guide the users to find the documents of their language.

Perhaps,

- Increase the size of the header
- Add flag emojis to each language items
- and so on...

might be working.

We are already using [gatsby-plugin-i18n](https://github.com/angeloocana/gatsby-plugin-i18n), so SEO and prerendering wouldn't be the cause of feedback.

**Comment by bluebill1049** [comment]
sounds good to me @adhrinae. will update the design.

**Comment by bluebill1049** [comment]
<img width="540" alt="Screen Shot 2020-08-08 at 2 09 53 pm" src="https://user-images.githubusercontent.com/10513364/89702117-d7ee9580-d980-11ea-8326-40f0e5b7edcd.png">

Mobile size increase:

14px to 16px

<img width="700" alt="Screen Shot 2020-08-08 at 2 12 14 pm" src="https://user-images.githubusercontent.com/10513364/89702151-2ac84d00-d981-11ea-96bc-8712af673400.png">

update table position

and desktop:
<img width="1678" alt="Screen Shot 2020-08-08 at 2 14 04 pm" src="https://user-images.githubusercontent.com/10513364/89702169-6d8a2500-d981-11ea-8b13-8169dfe9c579.png">

let me know your thoughts.

**Comment by adhrinae** [comment]
Looks better for me 🙂
Let's try this design.
