### ISSUE TITLE
Missing space between `to` and `useForm()` in `/api`

### ISSUE THREAD

**Issue by etasbasi** [react-hook-form/documentation#421]
Small typo in [api page](https://react-hook-form.com/api). Under the `defaultValues` section.

> You can set an input's default value with defaultValue/defaultChecked (read more from the React doc for Default Values), pass defaultValues as an optional argument **touseForm()** to populate the default values for the entire form, or set values on an individualController component via its defaultValue property.

I did a quick search but couldn't find the file where the typo is.

**Comment by pmaier983** [comment]
Thank you for bringing this to our attention etasbasi!
