### ISSUE TITLE
API documentation: description of mode="onTouched" is unclear

### ISSUE THREAD

**Issue by marko-knoebl** [react-hook-form/documentation#445]
At the the moment the API documentation on mode="onTouched" of useForm says:

    Validation won't trigger until input is touched (has lost focus).

As a newcomer this was rather unclear for me - especially I couldn't figure out the difference between "onTouched" and "onBlur".

After experimenting a bit I would describe the behavior like this:

    Validation will trigger on the first blur. After that, it will trigger on every change.

(the documentation page is here: <https://react-hook-form.com/api/#useForm> )

**Comment by bluebill1049** [comment]
send us a PR.
