### ISSUE TITLE
Importing resolver not working as expected for schema validation

### ISSUE THREAD

**Issue by kalaivanan-muthusamy** [react-hook-form/documentation#447]
When I upgrade the react-hook-form to V6, I faced below module resolving error

Code:  `import { yupResolver } from "@hookform/resolvers"`
Expected behavior: `yupResolver ` should be imported 
Actual behavior: Build is failed and getting error as `Module not found: Can't resolve '@hookform/resolvers'`

Resolution:  `import { yupResolver } from "@hookform/resolvers/yup"`. 

Not sure this is specific to some bundlers (I am using CRA with webpack). If, this is an issue from doc, I can update the document through PR.

**Comment by bluebill1049** [comment]
fixing the doc now thanks.

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2020-10-12 at 7.39.38 pm.png…]()
wait the doc is correct.

**Comment by kalaivanan-muthusamy** [comment]
I found the reference in https://react-hook-form.com/get-started#SchemaValidation

![image](https://user-images.githubusercontent.com/20736832/95750385-af558580-0cba-11eb-8b61-239436b841c1.png)

**Comment by bluebill1049** [comment]
oh thanks! fixing it.
