### ISSUE TITLE
Can you store Dark/Light mode settings for the docs in local storage to persist for users?

### ISSUE THREAD

**Issue by idrisakmal** [react-hook-form/documentation#468]
**Is your feature request related to a problem? Please describe.**
I have to set the docs to light mode everytime I load the page. Would be nice to have it persist for each user's settings

**Describe the solution you'd like**
Light/Dark mode settings persist for each user 

**Describe alternatives you've considered**
store the settings in local storage

**Comment by pmaier983** [comment]
this Issue was fixed by #469 😄 Thank you @idrisakmal!

**Comment by idrisakmal** [comment]
thank you @pmaier983 !

**Comment by amankkg** [comment]
![image](https://user-images.githubusercontent.com/3933028/100567871-c1839580-32f3-11eb-9443-68c8a579c4ea.png)
This what I see on every visit. Even if I toggle it to the dark mode on the next visit it's light and links are invisible

**Comment by bluebill1049** [comment]
hmmm looks like it's still working...

**Comment by bluebill1049** [comment]
really strange, that's not even dark or light mode.

**Comment by bluebill1049** [comment]
looks like dark mode is set correctly.

**Comment by pmaier983** [comment]
The issue seems to be relegated to the header. I am able to create it when I go to the official website after clearing all the sites data locally, but I am unable to replicate the issue locally.

**Comment by bluebill1049** [comment]
strange... I will spend some time tonight on this issue. plan b just update in local storage and keep away from the auto detect.

**Comment by pmaier983** [comment]
So I did some sleuthing, It seems on initial load there is some confusion as to what theme to display in. It's almost as if some components cant actually see/use `state?.setting?.lightMode`

**Comment by bluebill1049** [comment]
@amankkg let us know if this is fixed. Thanks @pmaier983's fix!

**Comment by pmaier983** [comment]
I think we should force everyone to default to dark mode (the way it worked before) because as it is now, a new user logging in sees some very odd colors. I'll keep investigating the reason in the background, but this would be a good quick fix.

**Comment by bluebill1049** [comment]
I agree @pmaier983 I did some investigation as well. It's a strange one probably something i did wrong by using Gatsbye. i even debug prod build and all the flag was correct.

**Comment by pmaier983** [comment]
I'm going to be closing this issue now. We are currently defaulting to dark mode as of this commit: https://github.com/react-hook-form/documentation/commit/52590ce9714004b9d2354d8af52f4e15b0f2d1f8

**Comment by bluebill1049** [comment]
Thanks @pmaier983

**Comment by amankkg** [comment]
Yep, now it works as expected! Thanks @pmaier983
