### ISSUE TITLE
no possibility to add & remove new items to the virtualized list

### ISSUE THREAD

**Issue by Quernest** [react-hook-form/documentation#477]
@bluebill1049 

Thanks for the [fix](https://github.com/react-hook-form/documentation/commit/cc1a77a3401803703740cb171df7248d5bd2dcea) and again regarding #476 

There is a problem - the example works correctly for only static lists. For example, is it possible to add a new element (input) or remove one from the middle? I can't find a way.

Storing items in the state and adding / removing items from the state does not bring the desired result. Elements are removed only from the end.

See [CodeSandbox](https://codesandbox.io/s/react-hook-form-with-react-window-forked-2n3fd?file=/src/index.js)

I've also tried the one designed for this particular case, but it doesn't work with virtual lists - https://react-hook-form.com/api#useFieldArray

**Comment by bluebill1049** [comment]
not sure if we support that usage, what about if you try `useFieldArray` with `shouldUnregister: false`, then just map with virtual `Controller`

`{fields.map(() => <Controller name="xxxx" />)}`

**Comment by Quernest** [comment]
> 
> 
> not sure if we support that usage, what about if you try `useFieldArray` with `shouldUnregister: false`, then just map with virtual `Controller`
> 
> `{fields.map(() => <Controller name="xxxx" />)}`

Deleting elements works correctly, but the data in the inputs is not updated. You can try to change value in 1 input, and then scroll down and up - the value will resetted. But, if you change value in 1 input, and then delete the second input, then the data will be saved and nothing is reset on the scroll 🤷‍♂️

https://codesandbox.io/s/clever-galois-ezj2l?file=/src/App.js

**Comment by bluebill1049** [comment]
Try this: https://codesandbox.io/s/elated-cloud-1r8ip?file=/src/App.js

**Comment by Quernest** [comment]
> 
> 
> Try this: https://codesandbox.io/s/elated-cloud-1r8ip?file=/src/App.js

Thanks a lot, it seems to be working as it should 🎉

---

I also found 1 interesting bug (?) with appending new fields.

Create a new input and fill it with some value, then create a new input - the new input will have the same value as in the previous one.

You can test it here:
https://codesandbox.io/s/smoosh-firefly-be6x6?file=/src/App.js 

```js
const EMPTY_FIELD = {
  title: "",
  quantity: ""
};

const { fappend } = useFieldArray({ control, name: "test" });

// ❌ bug?
<button onClick={() => append(EMPTY)}>append</button>

// ✅ works fine
<button onClick={() => append({ title: '', quantity: '' })}>append</button>
```

**Comment by bluebill1049** [comment]
fixing it 👍
