### ISSUE TITLE
setup.native.ts not found

### ISSUE THREAD

**Issue by EdnilsonCS** [react-hook-form/documentation#487]
I'm trying to configure jest to use in a react native project. but the documentation tells me to set up a file called setup.js. the problem is that this file mentioned in the documentation does not exist.

this is the link quoted: https: //github.com/react-hook-form/react-hook-form/blob/master/setup.native.ts
it is quoted in the react-hook-form advanced settings for react native: https://react-hook-form.com/advanced-usage#TestingForm.

please update the docs so that i can know which procedures i should follow.

Thanks for listening.

**Comment by EdnilsonCS** [comment]
I opened the following pull request by updating the English docs: https://github.com/react-hook-form/documentation/pull/488

**Comment by bluebill1049** [comment]
thanks for fixing it. ❤️
