### ISSUE TITLE
Accepting info@example as correct email format and not returning any error

### ISSUE THREAD

**Issue by kamleshwebtech** [react-hook-form/documentation#491]
It is accepting info@example as correct email format and not returning any error of validation and form is being submitted. What is the solution? Is this bug or need to add any special functionality of react-hoom-form? Kindly suggest.

and also update "Live Demo" section for the same at https://react-hook-form.com Thanks a lot.

For more information, please see attached screenshot of https://react-hook-form.com website.

![Home-React-Hook-Form-Simple-React-forms-validation](https://user-images.githubusercontent.com/43021973/102981369-db994800-452e-11eb-9250-929930b421e8.png)

**Comment by bluebill1049** [comment]
<img width="1425" alt="Screen Shot 2020-12-24 at 8 02 53 am" src="https://user-images.githubusercontent.com/10513364/103036677-6e34f800-45be-11eb-96ca-da91e6e0fe1e.png">

you can update that `regex` in the build, we are just using a very weak regex for the dmeo.
