### ISSUE TITLE
Derive some of the documentation from the code's Typescript

### ISSUE THREAD

**Issue by andrewbusch7** [react-hook-form/documentation#496]
Correct me if I'm wrong, but at the moment, the documentation always needs to be manually changed for any changed to exposed types in react-hook-form, even if the change is trivial. To lighten the maintenance overhead, has there been any investigation or thought into programmatically deriving what is relevant from the typings? E.g. `useFieldArray()`'s `append()` has the TS signature:

```ts
append = (
    value: Partial<TFieldArrayValues> | Partial<TFieldArrayValues>[],
    shouldFocus = true,
) => void
```

which is pretty decent documentation as is. Then, hypothetically let's say `shouldFocus` becomes not optional, the documentation could be updated simply by version bumping the dependency on `react-hook-form`.

Just spitballing here though. I'm also concurrently envisioning a framework for JS packages that's like Storybook for React component libraries – make documentation sites easier. Derive what is possible from TS/JSDoc then extend/rearrange as desired.

**Comment by pmaier983** [comment]
Hey @andrewbusch7. I like this idea alot, it would 100% cut down on overall time spent tweaking documentation. If you end up creating a library that could do this (or find one) update us!

**Comment by bluebill1049** [comment]
💯

**Comment by andrewbusch7** [comment]
Ok great, I'll do some research then!

**Comment by andrewbusch7** [comment]
I had a look into it, doesn't look like there's anything considerable out there. It seems that you'd have to use the Typescript compiler, examples here: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API. It'd be an interesting project but not at the top of my list for now. I imagine it'd be rather involved to build.
