### ISSUE TITLE
Add link to example error object

### ISSUE THREAD

**Issue by vicasas** [react-hook-form/documentation#500]
As new to this library, I wanted to give it a try on an ecommerce project manipulating my forms and it was a huge headache to find out how to customize the error messages for my input fields.

I went straight to the `register` api assuming there should be detailed information on the subject and that it is fine, it explains that it can be done, but it does not show how it is done.

I suggest adding a link in the text "You can assign a string to return an error message in the errors object". to the [Error Message](https://react-hook-form.com/advanced-usage#ErrorMessages)

![image](https://user-images.githubusercontent.com/57921784/104470183-32c39300-5598-11eb-8d66-e75949574d59.png)

**Comment by bluebill1049** [comment]
there is a toggle button on the top, you probably miss it, maybe we should make it more obvious.

`Register with validation and error message`

**Comment by vicasas** [comment]
Yes, after a while I realized. The first few times I saw it I thought it was an example of the content above and did not care.

Maybe it would look better in Tabs?

I still think there should be a direct link to the error object documentation.
