### ISSUE TITLE
Small issue in documentation - Working with virtualized lists

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/documentation#505]
The following lines should be using the backtick (`) character instead of double-quotes (").

title: "List ${i}",
const qtyKey = "[${index}].quantity";

**Comment by bluebill1049** [comment]
Thanks @wdfinch if you got time, plz send us a PR. 👍

**Comment by wdfinch** [comment]
Might not be able to get to this for a few weeks since I have some tough deadlines right now. If it's not fixed when I have a moment, I will submit a PR.

**Comment by bluebill1049** [comment]
fixed in v7 doc.
