### ISSUE TITLE
Update migration guide with breaking changes to types

### ISSUE THREAD

**Issue by lauralouiset** [react-hook-form/documentation#543]
Breaking changes to types (I discovered with "UseFormMethods" type) not mentioned in the migration guide. This should at least be mentioned, it was a surprise!

https://react-hook-form.com/migrate-v6-to-v7/

https://github.com/react-hook-form/react-hook-form/commit/9555d16fbf409f7bd84f369c81ccc6f5acef8479#diff-15bf0633de9d47fac0f47e1beedf845c8cd4421de1024d213f8e50b698b25710

**Comment by bluebill1049** [comment]
Most of the Type have been renamed and at least keep consistency. you can take a  look at the change log here: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md

**Comment by bluebill1049** [comment]
I have included a paragraph in the migration doc to lead users to the TS page for the updated type names.
