### ISSUE TITLE
Please Add An Example For Control Component Usage In The Context Of useFieldArray In Version 7 With Typescript

### ISSUE THREAD

**Issue by dudiharush** [react-hook-form/documentation#547]
Please Add An Example For Control Component Usage In The Context Of useFieldArray In Version 7 With Typescript

**Is your feature request related to a problem? Please describe.**
my problem is I could never make this part work with Typescript
{...register(`test.${index}.value`)} 

the error message i got is:
"Types of property 'name' are incompatible.
Type 'string' is not assignable to type..."

**Comment by bluebill1049** [comment]
will include this one: https://codesandbox.io/s/calc-i231d

**Comment by dudiharush** [comment]
I saw your Sandbox example, and it's missing an example of how to use the returned fields from useFieldArray function and the control param inside a Controller component, and the name value of the string template with the index
