### ISSUE TITLE
Form values are undefined in react virtualized example 

### ISSUE THREAD

**Issue by shamseerahammedm** [react-hook-form/documentation#555]
The form values are `undefined` on submit of the form. All inputs are populated with correct values but value is only received if any of the fields are changed.

https://react-hook-form.com/advanced-usage#Workingwithvirtualizedlists

official sandbox url given in that page -> https://codesandbox.io/s/react-hook-form-with-react-window-forked-3j3mq?file=/src/index.js
a

**Comment by shamseerahammedm** [comment]
@bluebill1049 so you have changed the example used ? 
the example says "Rather than register fields, we use getValues and setValue."
i dont see `getValues ()` or `setValue()` used any where in the new example.

**Comment by bluebill1049** [comment]
> @bluebill1049 so you have changed the example used ?
> the example says "Rather than register fields, we use getValues and setValue."
> i dont see `getValues ()` or `setValue()` used any where in the new example.

It's no longer the case for v7. I will update the description as well.
