### ISSUE TITLE
rules for Controller component seems invalid for TypeScript

### ISSUE THREAD

**Issue by s-KaiNet** [react-hook-form/documentation#557]
**Describe the bug**

As per [controller's documentation](https://react-hook-form.com/api/usecontroller/controller) it accepts `rules` object in the same format as for register. `register` contains different validation rules including `valueAsNumber`, `valueAsDate`.   

However, for TypeScript we have the below definition for controller:   

```
export declare type UseControllerProps<TFieldValues extends FieldValues = FieldValues, TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>> = {
    name: TName;
    rules?: Omit<RegisterOptions, 'valueAsNumber' | 'valueAsDate' | 'setValueAs'>;
....
};
```

which makes it impossible to set `valueAsNumber` rule for a `<Controller rules={{...}}`... />.   

I'm just not sure on which side the bug is - in documentation (we cannot use **same** rules for controller as for register) or in TS declaration file - should be just `rules?: RegisterOptions`?

**Comment by sarahhublo** [comment]
@bluebill1049 Hello, 
I was using `setValueAs` within `rules` of a controller. 
Now I am migrating from v6 to v7, I am having issue with this, setValueAs is not available anymore on "rules" do you have an alternative ?

Thank you very much

**Comment by bluebill1049** [comment]
> @bluebill1049 Hello,
> I was using `setValueAs` within `rules` of a controller.
> Now I am migrating from v6 to v7, I am having issue with this, setValueAs is not available anymore on "rules" do you have an alternative ?
> 
> Thank you very much

That was actually a bug and not intentional for v6, the value transform should happen in the controlled component level, as you can set state internally.

hope this section helps: https://react-hook-form.com/advanced-usage#TransformandParse
