### ISSUE TITLE
Documentation does not render backslashes in regex

### ISSUE THREAD

**Issue by chrisdrifte** [react-hook-form/documentation#560]
Lost more minutes of my life than I'd have liked before I realised this issue haha.

The regex `/\S+@\S+\.\S+/` is correct on [codesandbox ](https://codesandbox.io/s/react-hook-form-unit-test-docs-066zk?file=/src/App.js:695-715), but renders as `/S+@S+.S+/` [in the docs](https://react-hook-form.com/advanced-usage/).

Copy & pasting the example code results in a form with broken error handling, which is confusing.

**Comment by bluebill1049** [comment]
send us a PR.

**Comment by chrisdrifte** [comment]
I've tried to be helpful by reporting an issue. I'm certainly not the person in the best position to be responsible for fixing it.
