### ISSUE TITLE
Migration from v6 to v7 - confusing example

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/documentation#567]
I just want to say that I successfully migrated to v7, but the example in the documentation is a bit confusing:

https://github.com/react-hook-form/documentation/blob/2edbfd8e5de1972e03919ee33fb63c816f994f93/src/pages/migrate-v6-to-v7.en.tsx#L119-L124

First input has name `test` and then "after migration" is `name` (not `test`).
Also, not sure why we have there in diff line with `TextInput`, as it is not needed - we might want different example for MaterialUI.

**Comment by bluebill1049** [comment]
thanks @michalbundyra get this sorted now.
