### ISSUE TITLE
Getting started guide - provide section links. Please :D

### ISSUE THREAD

**Issue by losrobbos** [react-hook-form/documentation#575]
Buongiorno Bill!

Thank you for your awesome library!

I am a web development teacher and I show your React Hook Form library in classes a lot. Students really enjoy it :100: 

But: It is very difficult for me to provide people with guidance on their individual issues. Often I quickly wanna show them a example snippet from the official documentation, e.g. how to do validation error display.

It would be super helpful if - in your Getting Started guide: https://react-hook-form.com/get-started - you would wrap your section headings with anchor tags, so one could provide a direct link to a section.

This would make looking up things so much more convenient and - because I see the daily confusion of the learners - I am sure the acceptance of your library would push even further through the roof :+1:

**Comment by bluebill1049** [comment]
hey, @losrobbos amazing to hear! thank you very much for the feedback as well.

Is this what do you mean? https://react-hook-form.com/get-started#Applyvalidation 

If that's what do you mean let me know in more detail, please. 

Thanks

**Comment by losrobbos** [comment]
Aaaah, @bluebill1049, thanks a lot for clarifying! It was already there :) 
I guess I am so used to the "clicking a section header" - like in GitHub READMEs - that I totally overlooked your menu navigation. 

Thanks a lot! That will make life now much easier

**Comment by bluebill1049** [comment]
all good 👍
