### ISSUE TITLE
Example of Schema Validation is not working on codesandbox

### ISSUE THREAD

**Issue by matoruru** [react-hook-form/documentation#577]
I tried to run this example via "CODESANDBOX" button at the upper-right of the code snippet: https://react-hook-form.com/get-started#SchemaValidation

It's not working for both JavaScript and TypeScript.

Once I hit the submit button in this form it's going to show this error:

```
TypeError
react_hook_form_1.transformToNestObject is not a function
    at Object.eval (https://eb41q.csb.app/node_modules/
hookform/resolvers/dist/yup.js:45:39
async eval
https://eb41q.csb.app/node_modules/react-hook-form/dist/index.esm.js:1047:50
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

**Comment by matoruru** [comment]
It happened on these codesandbox:

- JavaScript: https://codesandbox.io/s/react-hook-form-v7-validationschema-rm35t
- TypeScript: https://codesandbox.io/s/react-hook-form-validationschema-v7-ts-eb41q

**Comment by bluebill1049** [comment]
thank you. both fixed.

**Comment by matoruru** [comment]
Ahh super fast! 🥶 Thank you!
