### ISSUE TITLE
Small styling issue with the Version select on website

### ISSUE THREAD

**Issue by RockinRonE** [react-hook-form/documentation#581]
On Firefox I noticed this:

<img width="97" alt="Screen Shot 2021-05-09 at 7 15 25 AM" src="https://user-images.githubusercontent.com/8163241/117571935-5609d500-b096-11eb-8dae-885d2325bad6.png">

Setting the select style from `width: 70px` to `width: auto;` resolves this issue, but I couldn't find a way to create a PR for the website. If there's a way to do this please let me know!

**Comment by bluebill1049** [comment]
hey @RockinRonE thanks for the report, try to fork the repo and create a pull request. give it a shot, otherwise, I will resolve it later as well. thanks
