### ISSUE TITLE
setValueAs is shown in V5 documentation

### ISSUE THREAD

**Issue by ramram1048** [react-hook-form/documentation#595]
Hi, I'm using react-hook-form V5 currently.

I just confused that there's an option for `setValueAs` in V5 documentation, but not was in [actual source code](https://github.com/react-hook-form/react-hook-form/blob/8bfbc059573f2411208a87f44446e2cb0a24d78a/src/useForm.ts). Maybe it's a new feature on V6 right?

**Comment by bluebill1049** [comment]
It's v6 plus feature.
