### ISSUE TITLE
docs should say deep merge

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/documentation#598]
The docs still state that form values will be shallowly merged. This should be deep merge now correct?

**Comment by bluebill1049** [comment]
There is really not deep merge :) but yea shallow should be updated, we only do shallow for the first render for getValues api.

**Comment by wdfinch** [comment]
ok

**Comment by wdfinch** [comment]
Maybe we could add a note on auto registering? I would volunteer but I not sure exactly how it works to be honest. We did not end up implementing the option in the RFC

**Comment by bluebill1049** [comment]
<img width="915" alt="Screen Shot 2021-05-28 at 11 51 37 am" src="https://user-images.githubusercontent.com/10513364/119918048-10606e00-bfab-11eb-8549-d0fe948ae650.png">

let me know if we need to add more on above.

**Comment by wdfinch** [comment]
Looks good! Is there anyway to disable this behavior? I would mention that too if it's possible.

**Comment by bluebill1049** [comment]
> Looks good! Is there anyway to disable this behavior? I would mention that too if it's possible.

It's not possible unless `deafultValues` is not included.

**Comment by wdfinch** [comment]
Ok looks good then! Also if we do this, do we even need the shallow merge? It's seems unnecessary if this does it and more.

**Comment by bluebill1049** [comment]
we don't only with getValues, in case user called register before getValues.
