### ISSUE TITLE
FieldArray TS Docs in v7

### ISSUE THREAD

**Issue by ivantm** [react-hook-form/documentation#602]
Hello 👋 

I'm having some difficulty upgrading from v6 to v7. A large chunk of the new type check errors appear to be related to the `FieldArray` type (which was `ArrayField` in v6) when custom key names are used.

[In the docs as they currently stand](https://react-hook-form.com/ts#FieldArray), this is shown for `FieldArray`:

```ts
export type FieldArray<
  TFieldArrayValues extends FieldValues = FieldValues,
  TKeyName extends string = 'id'
> = TFieldArrayValues & Record<TKeyName, string>;
```

However, the actual definition is more complex and doesn't seem to accommodate the custom key name any more.

```ts
export declare type FieldArray<
  TFieldValues extends FieldValues = FieldValues,
  TFieldArrayName extends FieldArrayPath<TFieldValues> = FieldArrayPath<TFieldValues>
> = FieldArrayPathValue<TFieldValues, TFieldArrayName> extends ReadonlyArray<
  infer U
>
  ? U
  : never;
```

It seems like what I'm after to replace the old `ArrayField` type (with custom key name) might be `FieldArrayWithId`, but that is more complex yet:

```ts
export declare type FieldArrayWithId<
  TFieldValues extends FieldValues = FieldValues,
  TFieldArrayName extends FieldArrayPath<TFieldValues> = FieldArrayPath<TFieldValues>,
  TKeyName extends string = "id"
> = FieldArray<TFieldValues, TFieldArrayName> & Record<TKeyName, string>;
```

I'm not sure what the `FieldArrayPath` type is or what I should be using for it - the typings are a bit too layered for me to make sense of.

Is there something really obvious that I'm missing, or are the TS docs incorrect (switching versions also doesn't seem to reflect that FieldArray was called ArrayField in v6)? 

Any pointers would be greatly appreciated 😅 (I'd be happy to open a PR to update the docs once I've made sense of it)

**Comment by bluebill1049** [comment]
oh yes, you are right. `FieldArray` type need to be updated to v7.
