### ISSUE TITLE
useFieldArray - additional documentation on append/prepend/insert focusName format

### ISSUE THREAD

**Issue by akhilpai** [react-hook-form/documentation#609]
Thank you for the wonderful project!

**Is your feature request related to a problem? Please describe.**
The v7 useFieldArray documentation mentions a append/prepend/insert focusName option I would like to use, but I am not what the name should be.

**Describe the solution you'd like**
An example with focusName in the documentation would be great. Ideally, the option would be more narrowly typed with a helpful typescript error.

**Describe alternatives you've considered**
I found the solution through the test:
https://github.com/react-hook-form/react-hook-form/blob/master/src/__tests__/useFieldArray/focus.test.tsx#L140

It's obvious in hindsight it would follow the same convention as the rest, but I had tried unsuccessfully a few times before.

**Additional context**
Feel free to close wontfix, focusName will be searchable in issues now.

**Comment by bluebill1049** [comment]
can you provide more context on how to improve the doc? Happy to improve on it.

**Comment by akhilpai** [comment]
In the [useFieldArray api doc](https://react-hook-form.com/api/usefieldarray/), maybe replace "and focus." with "and focus the field corresponding to either: 1) the fully qualified field name if focusName is set; 2) the field specified by focusIndex if it is set and focusName is not; 3) the field created by the action if neither is set.
https://github.com/react-hook-form/react-hook-form/blob/master/src/useFieldArray.ts#L110

One point of confusion for me is how focusIndex (and partial focusNames) should work for nested field arrays. In my use case, it would focus an arbitrary input. I would expect it would focus the first in either the field object keys or in the jsx elements. A note here would be helpful I think.

Another option could be to add an option accepting a union type and deprecate the current fields, although probably something to consider for a later version.

I'll send a PR this weekend if the above looks good.
