### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by lancemccluskey** [react-hook-form/documentation#628]
https://github.com/react-hook-form/documentation/blob/a72342d87f741763bc0873ef92c4af16fb681a5a/src/components/useForm/UnRegister.tsx#L125 

relevant screenshot:\

![Screen Shot 2021-07-09 at 10 54 08 AM](https://user-images.githubusercontent.com/40124399/125105359-ff277880-e0a3-11eb-9cdd-680ba33d229a.png)

I can do a followup PR for this once its validated!

### TLDR
Should be `keepError`, not `keepErrors`

**Comment by bluebill1049** [comment]
ty for reporting and the fix. 👍
