### ISSUE TITLE
Prop `rule` in Controller could use a dedicated paragraph

### ISSUE THREAD

**Issue by mbounaasferret** [react-hook-form/documentation#634]
Hi,

Just a small issue following the fact that I struggled to find / understand that we can use a `rule` prop on controllers to do validation on controlled fields.

Could the different native way of react-hook-form to handle validation be explained in a dedicated paragraph ?

**Comment by bluebill1049** [comment]
please ask questions here: https://github.com/react-hook-form/react-hook-form/discussions and best to follow with code and example
