### ISSUE TITLE
TypeScript doc page not returned by search

### ISSUE THREAD

**Issue by bard** [react-hook-form/documentation#664]
The main TypeScript doc page at https://react-hook-form.com/ts is not returned when searching for "typescript" using the on-site Algolia widget. (The word "TypeScript" appears no where in the page.)

**Comment by bluebill1049** [comment]
interesting @pmaier983 would you be able to help? you set up the search. 🙏

**Comment by pmaier983** [comment]
@bluebill1049 actually fixed this problem with this commit https://github.com/react-hook-form/documentation/commit/f97ccfa503605b2808aeb3ec0808a0226cb63710. Bill out here fixing bugs without even trying 💪🧠. 

![CleanShot 2021-09-11 at 17 13 11@2x](https://user-images.githubusercontent.com/35811186/132966555-e12af7f8-ec0c-4dbb-a0df-86b5c60ecb06.png)

I'm going to resolved this issue for now, but  @bard did bring up a good point, so i am going to create a PR changing some TS -> Typescript, allowing algolia a bit of an easier time prioritizing things.

**Comment by bluebill1049** [comment]
thank you @pmaier983
