### ISSUE TITLE
Demo for `watch` is broken

### ISSUE THREAD

**Issue by nvh95** [react-hook-form/documentation#681]
Demo for `watch` is broken.
https://react-hook-form.com/faqs#watchvsgetValuesvsstate

![image](https://user-images.githubusercontent.com/8603085/138326268-72a7a507-5c4d-409b-ac6d-8d2d78692514.png)

https://codesandbox.io/s/react-hook-form-watch-with-radio-buttons-and-select-examples-ovfus

**Comment by bluebill1049** [comment]
thanks fixed.

**Comment by nvh95** [comment]
It worked. Thank you @bluebill1049
