### ISSUE TITLE
Register spread operation error Typescript

### ISSUE THREAD

**Issue by jagajastic** [react-hook-form/documentation#691]
Definition
<img width="889" alt="Screenshot 2021-11-05 at 6 39 53 PM" src="https://user-images.githubusercontent.com/28712864/140586142-58d74d08-431d-411d-925b-d1a719943828.png">

Usage:

<img width="686" alt="Screenshot 2021-11-05 at 6 40 32 PM" src="https://user-images.githubusercontent.com/28712864/140586178-73edc572-84dd-40dc-8dc2-02fa5f488bda.png">

ERROR:
<img width="1068" alt="Screenshot 2021-11-05 at 6 39 08 PM" src="https://user-images.githubusercontent.com/28712864/140586079-fdb722a1-5dab-4796-a157-586b4eb7b58d.png">

**Comment by bluebill1049** [comment]
please refer tot he doc: https://react-hook-form.com/api/useform/register
