### ISSUE TITLE
doc: Improvement in code readability

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [react-hook-form/documentation#695]
In a [custom validator](https://codesandbox.io/s/react-hook-form-customresoliver-v7-8mpqw?file=/src/index.jsx) at API page on [`useForm`](https://react-hook-form.com/api/useform) topic:
I guess readability may be somewhat improved by not using ternary in the returned object.
Also, I return the object directly in the reduce and place it on the new line, aligning it with the accumulator.
Although it may appear to be an opinion, it is advised by prettier and I suppose it helps to obtain the most of the code in the first pass.

```jsx
 const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    context: "context",
    resolver: async (data, context) => {
      console.log(context);
      const { error, value: values } = validationSchema.validate(data, {
        abortEarly: false,
      });

      if (!error) return { values: values, errors: {} };

      return {
        values: {},
        errors: error.details.reduce(
          (previous, currentError) => ({
            ...previous,
            [currentError.path[0]]: currentError,
          }),
          {},
        ),
      };
    },
  });
```

**Comment by bluebill1049** [comment]
feel free to submit a PR if you have some free time 👍

**Comment by amirHossein-Ebrahimi** [comment]
I tried but it is internal codesand box, is it okay I fork sandbox and update the code?

**Comment by bluebill1049** [comment]
ooops thanks @amirHossein-Ebrahimi i have updated it, let me know if that's fixed.

**Comment by amirHossein-Ebrahimi** [comment]
It is not fixed yet, actually, sandbox got updated, but the code viewed in the doc is not yet updated.

- I disabled my cache
- I also, opened tab in new incognito 

maybe it needs something else to be updated. Feel free to close the issue by yourself, if it got fixed :)
