### ISSUE TITLE
fix: imprecise comment message

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [react-hook-form/documentation#696]
📁  APIs / 📁 [register](https://react-hook-form.com/api/useform/register) / 📁 Custom onChange, onBlur

```jsx
// onChange got overwrite by register method
<input onChange={handleChange} {...register('test')} />

// register's onChange got overwrite by register method
<input {...register('test')} onChange={handleChange}/>
```

the second comment must be changed to something like:
- `register's onChange got overwritten by custom onChange props`
- `register's onChange got overwritten by handleChange`
- `register's onChange got overwritten by given onChange props`

Also, the first comment can be improved grammatically to something like
- `onChange got overwritten by register's method`
- `onChange got overwritten by register's onChange method`
- `onChange prop got overwritten by register's method`

**Comment by bluebill1049** [comment]
thanks 👍 PR welcome.
