### ISSUE TITLE
docs: typo in handleSubmit API reference

### ISSUE THREAD

**Issue by akashshyamdev** [react-hook-form/documentation#701]
### Steps to reproduce

1. Go [here] (https://react-hook-form.com/api/useform/handlesubmit)
2. Scroll to the video section
3. The error is "The following video tutorial explain in detail withhandleSubmit API."

### Expected behaviour

The sentence should be "The following video tutorial explains the handleSubmit API in detail."

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Contribution
If you see this as a valid problem, I'm happy to make a PR for it 😊 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
this is the repo.

**Comment by akashshyamdev** [comment]
Ah thanks, couldn't find the repo 😅
