### ISSUE TITLE
issue: valueAsNumber use contradicts W3C specs

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/documentation#722]
### Version Number

7.25.3

### Codesandbox/Expo snack

https://codesandbox.io/s/loving-sanderson-ivkjy?file=/src/App.tsx

### Steps to reproduce

1. Go to [this CSB](https://codesandbox.io/s/loving-sanderson-ivkjy?file=/src/App.tsx)
2. See TS error `Property 'valueAsNumber' does not exist on type 'EventTarget & HTMLSelectElement'.ts(2339)` in the second `<select />` element's `onChange` callback

### Either
- The RHF behavior is replicating the [W3C specs](https://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#dom-input-valueasnumber): `valueAsNumber`doesn't apply to non-numeric, non-data input elements
> if the valueAsNumber attribute does not apply, as defined for the input element's type attribute's current state, then return a Not-a-Number (NaN) value
- [RHF docs](https://react-hook-form.com/api/useform/register/#registerRef) state that the behavior is due to W3C specs
```
valueAsNumber: Only applies to text input. (due to [W3C specs ref])
```
### or
- RHF supports `valueAsNumber` for select input elements
- [RHF docs](https://react-hook-form.com/api/useform/register/#registerRef) clearly state that it supports `valueAsNumber` for `select` input element despite the [W3C specs](https://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#dom-input-valueasnumber).

# Additional Information
See  how other libs deal with the question: ampproject/amphtml/issues/11513

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Property 'valueAsNumber' does not exist on type 'EventTarget & HTMLSelectElement'.ts(2339
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I do think it's a handy "bug not feature" _(insert comma where appropriate)_. So, yeah, I'd leave it as is and update RHF docs to exclude the
```text
valueAsNumber: Only applies to text input
```
Maybe update the docs to include that it actually works with select input, despite the W3C. I wouldn't say "**not** the intended behavior", but it's just my POV

**Comment by bluebill1049** [comment]
>Maybe update the docs to include that it actually works with select input, despite the W3C. I wouldn't say "not the intended behavior", but it's just my POV 

My only concern is because it's "supported", then users would come up with usage which we do not support and make things even worse.

**Comment by Moshyfawn** [comment]
Aaah, I see your point! Hm..
Maybe just remove the
```text
valueAsNumber: Only applies to text input
```
then?

If you wanna state that the behavior wasn't intended, go for it. It just feels weird to me to see "we've created a cool behavior which is actually a bug" in lib docs lol xD

**Comment by bluebill1049** [comment]
Thanks, @Moshyfawn will get that updated and keep it clear. 👍
