### ISSUE TITLE
Invalid destructuring in getFieldState doc

### ISSUE THREAD

**Issue by Josyto** [react-hook-form/documentation#733]
I have noticed a syntax which is similar to the destructuring one, but which is not valid.

![image](https://user-images.githubusercontent.com/18529351/154131740-526f611c-07f0-48d3-b2b3-ba83acf9eb39.png)

https://github.com/react-hook-form/documentation/blob/5db87ec4e581ccabda03b842e449a0255d2569d9/src/components/useForm/GetFieldState.tsx#L177

**Comment by bluebill1049** [comment]
thanks, feel free to send a PR next time as well 👍
