### ISSUE TITLE
docs: wrong usage example for handleSubmit with catch

### ISSUE THREAD

**Issue by lynxtaa** [react-hook-form/documentation#735]
https://react-hook-form.com/api/useform/handlesubmit

Right now usage example is
```js
const onSubmit = () => {
  throw new Error('Something is wrong')
}

handleSubmit(onSubmit).catch((e) => {
  // you will need to catch that error
})
```

But `handleSubmit` returns a function, not a promise. AFAIK it should be:
```js
const onSubmit = () => {
  throw new Error('Something is wrong')
}

event => handleSubmit(onSubmit)(event).catch((error) => {
  // you will need to catch that error
})
```

CodeSandbox https://codesandbox.io/s/react-hook-form-catch-plu1ow?file=/src/App.tsx

Thank you!

**Comment by bluebill1049** [comment]
thanks @lynxtaa you are right.
