### ISSUE TITLE
light mode: Button alignment is disturbed

### ISSUE THREAD

**Issue by sumant-k** [react-hook-form/documentation#748]
### Version Number
latest documentation site.

### Steps to reproduce

1. Go to [documentation](https://react-hook-form.com/).
2. Switch to **light mode**.
3. Check button toggle group **"React Web"** and **"React Native"** below the video.
4. Try toggling the two views
5. Button alignments from toggle group is getting disturbed in light mode.

### Expected behavior

Button alignment should stay the same in both light or dark mode

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant Info

**"React Native"** button's CSS property **border: 0;** is being overridden.
##### Possible fix: (to **.toggleGroup > button:last-child**)

```diff
- border-left: 0;
+ border-left: 0 !important; 
```

**Comment by bluebill1049** [comment]
thanks for the issue, feel free to send us a PR if you have the correct fix. could you share a video of the actual issue as well?
