### ISSUE TITLE
How to switch languages in the website

### ISSUE THREAD

**Issue by xxxxue** [react-hook-form/documentation#754]
hi , Is there no option to select a language in the website?  

Like this 

![image](https://user-images.githubusercontent.com/32764266/161027487-5da4d30e-2356-48e8-932e-1dd8f3b063ec.png)

**Comment by bluebill1049** [comment]
we used to support multiple languages, but I just couldn't find enough time to translate all the content into a different language. so I have stopped doing so for v7.
（我以前是有翻译到其他的语言，但是一边要工作有要追加开源等等问题实在是没有时间做到。请见谅。）
