### ISSUE TITLE
The builder generate incorrect code if a field is not required

### ISSUE THREAD

**Issue by nvh95** [react-hook-form/documentation#762]
# What is the issue
- In the Builder playground, if it is an optional field. The code generated is incorrect. This one confuses me when I read documentation to make `radio input` works. 

Image:
![Bug incorrect code generated](https://user-images.githubusercontent.com/8603085/162566120-d76004a3-e7ca-4477-9d56-c987d8818cc7.png)

# How to reproduce
1. Head to https://react-hook-form.com/form-builder
2. Edit `Developer` field to unselect `Required`

**Comment by nvh95** [comment]
@bluebill1049 Just submit a PR to this issue :)

**Comment by bluebill1049** [comment]
thanks @nvh95
