### ISSUE TITLE
Light mode navbar is using a slightly heavier font

### ISSUE THREAD

**Issue by demberto** [react-hook-form/documentation#782]
![react-hook-form-docs-bug](https://user-images.githubusercontent.com/65948403/172903811-1c05cf5d-cae1-421d-b508-840b48954954.gif)

*On a side note, yours is one of the best docs, not even big project funded by big companies have such good docs*

**Comment by bluebill1049** [comment]
thanks for the feedback. let us know if you have some preferred designs.

**Comment by demberto** [comment]
> let us know if you have some preferred designs.

Yeah, you could use the same font

**Comment by A-ASAD** [comment]
@bluebill1049 I can do this. Let me know if this enhancement is needed. Thanks

**Comment by bluebill1049** [comment]
yes plz @A-ASAD thank you 🙏
