### ISSUE TITLE
Builder example on main page does not work as described

### ISSUE THREAD

**Issue by EugeneDraitsev** [react-hook-form/documentation#799]
### Version Number

v7

### Codesandbox/Expo snack

https://codesandbox.io/s/spring-microservice-yn31u9

### Steps to reproduce

1. Go to ['form-builder'](https://react-hook-form.com/form-builder)
2. Copy default builder code:

```js
import React from 'react';
import { useForm } from 'react-hook-form';

export default function App() {
  const { register, handleSubmit, formState: { errors } } = useForm();
  const onSubmit = data => console.log(data);
  console.log(errors);
  
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input type="text" placeholder="First name" {...register("First name", {required: true, maxLength: 80})} />
      <input type="text" placeholder="Last name" {...register("Last name", {required: true, maxLength: 100})} />
      <input type="text" placeholder="Email" {...register("Email", {required: true, pattern: /^\S+@\S+$/i})} />
      <input type="tel" placeholder="Mobile number" {...register("Mobile number", {required: true, minLength: 6, maxLength: 12})} />
      <select {...register("Title", { required: true })}>
        <option value="Mr">Mr</option>
        <option value="Mrs">Mrs</option>
        <option value="Miss">Miss</option>
        <option value="Dr">Dr</option>
      </select>

      <input {...register("Developer", { required: true })} type="radio" value="Yes" />
      <input {...register("Developer", { required: true })} type="radio" value="No" />

      <input type="submit" />
    </form>
  );
}
```
3. Past it to any React project and check console logs https://codesandbox.io/s/spring-microservice-yn31u9

![image](https://user-images.githubusercontent.com/16540432/181579354-0c245fc4-2a86-43cc-ae0d-f75704ee8895.png)

4. There are no any error logs before I click submit

### Expected behaviour

I see the errors for "Mobile Number" field **before I click submit** as it shows in live demo of builder:

![image](https://user-images.githubusercontent.com/16540432/181579801-56682084-df71-49fb-bb84-7bf097e21a45.png)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
there is a whole section in the doc that describes this behavior: https://react-hook-form.com/api/useform It's a demo on the home page.

**Comment by EugeneDraitsev** [comment]
I understand that there is whole section in the doc about `reValidateMode`

My point is only about inconsistency between demo and code example:

![image](https://user-images.githubusercontent.com/16540432/181651786-56cacde4-de81-457a-851e-534afc772e4d.png)
When I click edit button and see the code:

![image](https://user-images.githubusercontent.com/16540432/181651860-07e37d66-4ca8-4ae8-8df6-1eeb5a12a477.png)

I expect that this code will work the same, as demo where I clicked on the "edit" button. 
But for some reason this code doesn't have `reValidateMode: onChange`  and behaves differently than the demonstrated behavior.

**Comment by getTobiasNielsen** [comment]
`reValidateMode: onChange` Is the default behavior, so it doesn't have to be added as argument, unless you what something different.

**Comment by getTobiasNielsen** [comment]
I assume this must be the issue. Maybe' it's better to add this mode to the code generated?
https://github.com/react-hook-form/documentation/blob/414ffbf5e9f1f80b4cbfe7050f8f0a13cca8babe/src/components/Form.tsx#L43-L45

**Comment by EugeneDraitsev** [comment]
yeah, with `mode: "onChange",` it works the same as in the demo. It would be great to add it to generated code
