### ISSUE TITLE
When in light mode, the text color of `Rules` in useFormContext is the same as the background and is unreadable. 

### ISSUE THREAD

**Issue by mochi-sann** [react-hook-form/documentation#811]
![screenshot 2022-08-31 19 12 04](https://user-images.githubusercontent.com/44772513/187655975-bc1203b2-c0c9-4175-8705-7536e266e9df.png)
https://react-hook-form.com/v6/api#useFormContext

When the `Rules' text in useFormContext is in light mode, as shown in the image, it is unreadable because it is white, the same color as the background.

**Comment by bluebill1049** [comment]
thanks, would you like to send us a PR, i believe just need to change the text into `currentColor`

**Comment by mochi-sann** [comment]
I sent you a pull request, please confirm.
