### ISSUE TITLE
Error in Code Example for 'watch'

### ISSUE THREAD

**Issue by SonicMagna** [react-hook-form/documentation#813]
Minor thing, but I'm just trying to help out.
https://react-hook-form.com/api/useform/watch
https://codesandbox.io/s/react-hook-form-watch-v7-qbxd7
Example code on the page has this line:
```const watchFields = watch(["showAge", "number"]); // you can also target specific fields by their names```
I think it should be:
```const watchFields = watch(["showAge", "age"]); // you can also target specific fields by their names```

**Comment by bluebill1049** [comment]
thanks fixed.
