### ISSUE TITLE
issue: setError has wrong CODESANDBOX linked.

### ISSUE THREAD

**Issue by slowWriting** [react-hook-form/documentation#816]
### Version Number

latest

### Codesandbox/Expo snack

webpage issue

### Steps to reproduce

1. Go to https://react-hook-form.com/api/useform/seterror/
2. Click on Examples->Single Field Errors
3. Click on CODESANDBOX
4. The code in codesandbox is different than the one in the example.

Same problem seems to happen with Single Error

### Expected behaviour

Links point to correct sandbox,

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by slowWriting** [comment]
Was a bit weird that the example did not contain setError function at all.
I'm currently fighting with setError not focusing on field and I was just checking every example, if I have missed anything.

**Comment by bluebill1049** [comment]
![Screen Shot 2022-09-06 at 8 19 26 pm](https://user-images.githubusercontent.com/10513364/188610798-69513efd-2320-44af-a008-2e2c059ff85b.png)

which example are you looking at? if the focus is not working, it's probably due to input `ref` is not forwarded or assigned.

**Comment by slowWriting** [comment]
This one:
![image](https://user-images.githubusercontent.com/6307557/188624714-266934e4-31a5-4d9b-8eaf-b418dccd933d.png)
https://codesandbox.io/s/react-hook-form-set-single-field-with-multiple-errors-ogf20

About the focusing, the ref is actually assigned from useController, I may create reproduction example.

**Comment by bluebill1049** [comment]
thanks. patching it.

**Comment by slowWriting** [comment]
About focusing, yes turned out it was ref problem. MUI Textfield ref will not cause focusing, inputRef prop has to be used.
