### ISSUE TITLE
The "Edit in GitHub" button often goes to the wrong page on GitHub

### ISSUE THREAD

**Issue by Dustin-Digitar** [react-hook-form/documentation#831]

**Comment by Dustin-Digitar** [comment]
Example:
https://react-hook-form.com/api/usefieldarray
->
useForm page

**Comment by bluebill1049** [comment]
want to send us a PR?

**Comment by griimick** [comment]
> Example:
> https://react-hook-form.com/api/usefieldarray
> ->
> useForm page

This looks good to me in master.


@bluebill1049 Is https://legacy.react-hook-form.com/ served from [V6-V5](https://github.com/react-hook-form/documentation/tree/v6-v5) branch? 

I could find the problem stated in this issue only in legacy docs but not in master. I can work on a PR to fix this issue.

**Comment by bluebill1049** [comment]
yes please @griimick thank you in advance.

**Comment by AdaltonLeite** [comment]
@bluebill1049 @griimick I think we solve this issue on the PR #868. Can we close this issue

**Comment by bluebill1049** [comment]
thanks @AdaltonLeite 🙏
