### ISSUE TITLE
Add/Replace TypeScript types for `UseFormReturn` section on `/ts` page

### ISSUE THREAD

**Issue by abdmmar** [react-hook-form/documentation#835]
## Overview

Currently `UseFormReturn` section is included examples about how to use the type, but there's no detailed type field for`UseFormReturn` itself. To make it easier for users to see what the `UseFormReturn` type is, I think we can add the type and persist the code examples like this:

![image](https://user-images.githubusercontent.com/50788123/193855936-8ebcef73-65c8-495f-976b-63bff310706f.png)

What do you think? I can help add the type if this is possible

**Comment by bluebill1049** [comment]
sounds good to me, please send us a PR 🙏
