### ISSUE TITLE
[Docs] Save user theme preference

### ISSUE THREAD

**Issue by michaeloliverx** [react-hook-form/documentation#838]
**Is your feature request related to a problem? Please describe.**
I use the docs of `react-hook-form` quite often and I always have to switch the theme back to light mode. 

**Describe the solution you'd like**
I would love if the website remembered my previous selection.

**Describe alternatives you've considered**
Manually doing it each time 😢 

**Additional context**

**Comment by bluebill1049** [comment]
Yea sure, PR welcome on this 👍
