### ISSUE TITLE
Error opening migration guides on website

### ISSUE THREAD

**Issue by amsimon** [react-hook-form/documentation#844]
### Version Number

7

### Codesandbox/Expo snack

https://react-hook-form.com/migrate-v6-to-v7/

### Steps to reproduce

1. Go to https://react-hook-form.com/migrate-v6-to-v7/ and https://react-hook-form.com/migrate-v5-to-v6
2. See 404 error

### Expected behaviour

Guides are displayed without 404 error.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Where is the original link? I can fix it? also there is a redirect PR: https://github.com/react-hook-form/documentation/pull/843 which gasby redirect is somewhat not working...

**Comment by amsimon** [comment]
@bluebill1049 I found those links by searching "react-hook-from migrate v5 to v6" on Google.

**Comment by bluebill1049** [comment]
oh i see, then that PR will need to be fixed in order to fix all the redirect thanks for letting us know.

**Comment by idoichev** [comment]
Wanted to create the same ticket, but fortunately found this one)
Any updates here? Maybe some estimates when migration guides can be reachable?
You also have mentioned original links, so maybe you can provide them meanwhile?

**Comment by bluebill1049** [comment]
going to add a client site redirect, for now, gatsby is not making it easy for me on this one...
