### ISSUE TITLE
Doc: resetOptions

### ISSUE THREAD

**Issue by LorhanSohaky** [react-hook-form/documentation#883]
There is no documentation explaining the `resetOptions` state reconciliation

**Comment by bluebill1049** [comment]
@LorhanSohaky let us know if any more information needs to supply or improve: https://github.com/react-hook-form/documentation/commit/60605c3fb24ab4b4f47c6969b19275ad79d478d9

**Comment by Moshyfawn** [comment]
LGTM!

**Comment by LorhanSohaky** [comment]
> @LorhanSohaky let us know if any more information needs to supply or improve: [60605c3](https://github.com/react-hook-form/documentation/commit/60605c3fb24ab4b4f47c6969b19275ad79d478d9)

Thks! It's perfect
