### ISSUE TITLE
/api/usecontroller/controller missing an object name

### ISSUE THREAD

**Issue by TonyGravagno** [react-hook-form/documentation#894]
I don't understand this: 
https://react-hook-form.com/api/usecontroller/controller

Why is this one property missing the `formState` object name?
![image](https://user-images.githubusercontent.com/499473/213292706-44978f93-852d-4abe-ad80-36bda343fff5.png)

Invoked from [ControllerContent.tsx](https://github.com/TonyGravagno/react-hook-form-website/blob/984ed3418573c54cbc19e5e4468dddbd96704cf9/src/components/ControllerContent.tsx#L47).

[API text](https://github.com/TonyGravagno/react-hook-form-website/blob/984ed3418573c54cbc19e5e4468dddbd96704cf9/src/data/en/api.tsx#L717) doesn't seem different from other props/args.

**Comment by bluebill1049** [comment]
would you like to send a PR on this?

**Comment by TonyGravagno** [comment]
I'd love to but honestly I don't know what's causing that little anomaly.
Thanks for all you do!!!!!! Have been re-re-re-watching your vids recently, and re-re-re-reading docs. :)

**Comment by bluebill1049** [comment]
all good, i will sort it out 👍
