### ISSUE TITLE
idea: Add a 3rd-party-bindings page to doc site

### ISSUE THREAD

**Issue by aranlucas** [react-hook-form/documentation#917]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to use react-hook-form with an external component library. It feels like it should be a "solved" problem but it ends up needing to re-invent every time due to each libraries quirks.

**Describe the solution you'd like**
I want a page similar to https://formik.org/docs/3rd-party-bindings showing 3rd party bindings for common libraries (if available.) If it's not available, at least you'll have an idea of how to best wire up RHF with these external component libraries. Note: react-hook-form doesn't need to own them.

**Describe alternatives you've considered**
Each person individually asks "How do I use 'react-hook-form' with X component library"

**Additional context**
I created a library that hooks up mantine and react-hook-form using the name prop.

https://github.com/aranlucas/react-hook-form-mantine

https://codesandbox.io/s/react-hook-mantine-krflqj?file=/src/App.tsx

There's also https://www.npmjs.com/package/react-hook-form-mui

**Comment by aranlucas** [comment]
I can take it up.

Are you thinking something like

```
- Articles/Blog
- Newsletter
- Videos
- 3rd party bindings ?
```

Or would it be merged somewhere in the current sections?

**Comment by bluebill1049** [comment]
I think it's best to have 4 pages, however, if with time constraining merge into a single page is a great addition as well.

**Comment by aranlucas** [comment]
I'll start with single page, and then work on separating so it's easier to consume.

I'm encountering an issue that is making this change take longer than expected. 

It seems https://github.com/react-hook-form/documentation/commit/8a322483f76dd4075647da2464d10ef5aea28b43 changed the data source from https://github.com/react-hook-form/documentation/blob/master/src/data/resources.tsx to https://github.com/react-hook-form/documentation/blob/master/src/components/Resources.json

If it's `Resources.json`, then the "Edit page" at the bottom does not redirect to the right page. If it's `resources.tsx`, then it's not currently up to date with the latest `Resources.json`

I'm thinking of removing `Resources.json` and moving back to using `resources.tsx` (Replacing `resources.tsx` content with whatever is in `Resources.json` ). 

Curious if there's something I'm missing here.

Thanks

**Comment by bluebill1049** [comment]
I have merged it for now, it looks good and additional resource for devs.

**Comment by aranlucas** [comment]
Thank you!

Regarding `I think it's best to have 4 pages`, do you have any mockups of how that might look like?

I think rather than splitting it up, might be worth to paginate the items on there similar to https://cloudscape.design/components/cards/?tabId=playground where the cards can be on the same page but are just limited to 10/page (reducing the amount of scrolling to get to the bottom.)

Could even have some sorting involved.

**Comment by bluebill1049** [comment]
> https://cloudscape.design/components/cards/?tabId=playground

That looks great! 4 page works better for SEO, I think if we can duplicated those pages and turn them into 4 is also a good choice, but what you have done is already excellent, hopefully SEO pick it up quickly.

**Comment by bluebill1049** [comment]
Awesome work here: https://github.com/aranlucas/react-hook-form-mantine 🥳

**Comment by aranlucas** [comment]
![Screenshot 2023-03-14 120011](https://user-images.githubusercontent.com/6351530/225109848-6c91ab67-051d-4a58-bc7b-e76d1471d027.png)

Here's my current idea for resource page to try and reduce the amount of scrolling on the page.

Just want to make sure we are on the same page.

With this it seems I'm separating them into 4 different containers, so next step to pages shouldn't be too bad.

**Comment by bluebill1049** [comment]
This looks great. Could we split it into different pages? 

/resources/articles
/resources/third-party-bindings
/resources/videos

The only concern is that pagination would not be a great way to help crawlers index content.

**Comment by aranlucas** [comment]
What would be in the 

/resource page?

or just change the navbar to have a dropdown similar to tools section?

**Comment by bluebill1049** [comment]
> or just change the navbar to have a dropdown similar to tools section?

yes, thanks for looking into this 👍
