### ISSUE TITLE
issue: Confusing useWatch documentation

### ISSUE THREAD

**Issue by RamonEspinosa** [react-hook-form/documentation#927]
### Version Number

7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/headless-shadow-i6brkl?file=/src/App.js

### Steps to reproduce

1. Calling `useWatch` with a string (the field name) as an argument will return all form values.

### Expected behaviour

According to `useWatch` [documentation](https://react-hook-form.com/api/usewatch/#main), one could call `useWatch` passing a string as an argument and it would return the field's value.
![image](https://user-images.githubusercontent.com/47266830/228669501-18efdab1-25d4-4104-84d2-aef43c46f22a.png)
This is not the case.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks that's a mistake, would you like to fix that with a PR?

**Comment by RamonEspinosa** [comment]
> thanks that's a mistake, would you like to fix that with a PR?

I can fix it if no one else offer themselves by the weekend

**Comment by bluebill1049** [comment]
Thank you so much in advance 🙏

**Comment by RamonEspinosa** [comment]
Hey @bluebill1049, I'll be working on this over the weekend.
I believe there are two ways to solve this issue and would like to get your opinion on which way to follow:
1. Update the documentation
2. Change the code a bit to also accept a string as a parameter

**Comment by bluebill1049** [comment]
Option 1, thanks 🙏
