### ISSUE TITLE
Controller rules in React Native don't work

### ISSUE THREAD

**Issue by ray-holland-es** [react-hook-form/documentation#938]
As far as I can tell, the <Controller> rules for react native don't do anything, they are not setting any errors.

Also the CodeSandbox link for the `rules` here: https://react-hook-form.com/api/usecontroller/controller/

doesn't work and has a 500 error. https://codesandbox.io/s/controller-rules-ipynf

**Comment by bluebill1049** [comment]
Please use the latest version and the CSB is working 
<img width="1001" alt="Screenshot 2023-04-12 at 8 37 56 am" src="https://user-images.githubusercontent.com/10513364/231303876-11ee05c4-ce4c-467d-a272-01156f549d15.png">
