### ISSUE TITLE
Improve `useFormState` code example

### ISSUE THREAD

**Issue by nakaakist** [react-hook-form/documentation#951]
The current code example of [`useFormState`](https://react-hook-form.com/api/useformstate/) consists of one `App` component.

However, to demonstrate that `useFormState` is effective in isolating re-renders, it would be more appropriate to include a child component, similar to the [`useWatch`](https://react-hook-form.com/api/usewatch/) example.

Below is the suggested code.

```tsx
import * as React from "react";
import { useForm, useFormState } from "react-hook-form";

function Child({ control }) {
  const { dirtyFields } = useFormState({
    control
  });

  return dirtyFields.firstName ? <p>Field is dirty.</p> : null;
}

export default function App() {
  const { register, handleSubmit, control } = useForm({
    defaultValues: {
      firstName: "firstName"
    }
  });
  const onSubmit = (data) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input {...register("firstName")} placeholder="First Name" />
      <Child control={control} />

      <input type="submit" />
    </form>
  );
}

```

https://codesandbox.io/s/useformstate-forked-gfio8i?file=/src/App.js:0-654

**Comment by bluebill1049** [comment]
would you like to send us a PR?

**Comment by nakaakist** [comment]
Yes, I created a PR! https://github.com/react-hook-form/documentation/pull/967
