### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by therealchewbecca** [react-hook-form/documentation#955]
Good afternoon! I just wanted to let you know there are some broken links in the docs:
https://react-hook-form.com/api/useform/watch/
https://react-hook-form.com/api/useform/reset/
https://react-hook-form.com/api/useform/resetfield/
https://react-hook-form.com/api/useform/seterror/
https://react-hook-form.com/api/useform/setfocus/
https://react-hook-form.com/api/useform/getvalues/
https://react-hook-form.com/api/useform/getfieldstate/
https://react-hook-form.com/api/useform/form/

**Comment by bluebill1049** [comment]
thanks will look into those cc @@aranlucas

**Comment by aranlucas** [comment]
Seems the website is in a weird state after nextjs deployment. 

/api/ is a reserved route in nextjs, and was renamed to /docs

Example 
* https://react-hook-form.com/docs/useform/watch/
* https://react-hook-form.com/docs/useform/reset/
* https://react-hook-form.com/docs/useform/resetfield/
* https://react-hook-form.com/docs/useform/seterror/
* https://react-hook-form.com/docs/useform/setfocus/
* https://react-hook-form.com/docs/useform/getvalues/
* https://react-hook-form.com/docs/useform/getfieldstate/
* https://react-hook-form.com/docs/useform/form/

Another interesting bit is that if you start the navigation through the /docs link, it's using the nextjs. But if you just navigate through the the main page, you'll see it's the gatsby site. (Can be confirmed by examining <div id="__next" >

@bluebill1049 can you check if there's a TTL somewhere in the DNS settings?

Another thing to consider is running another algoria indexing to fix previous pages.

**Comment by aranlucas** [comment]
I think just clearing browser cache worked for me to always redirect to nextjs site. But others might be stuck in this loop for a while until cache expires

**Comment by bluebill1049** [comment]
I will take a look at it tonight @aranlucas

**Comment by bluebill1049** [comment]
Please make sure to unregister service worker

https://twitter.com/HookForm/status/1660443884441460736
