### ISSUE TITLE
can't access to the docs

### ISSUE THREAD

**Issue by minkyung00** [react-hook-form/documentation#958]
I wanted to read the docs but I'm getting just blank pages.

I can access on `Home`, `Get Started` but can't access to some tabs on the docs.

- API
- TS
- Advanced
- FAQs

Just there is blank page on https://react-hook-form.com/api

<img width="500" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/80238096/1228d0f0-4cf3-4665-8a53-228b04e6d980">

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/documentation/issues/955#issuecomment-1556420672

**Comment by minkyung00** [comment]
@bluebill1049 
Thank you! I can read the document now 😎

But what does "unregister" mean in service worker? And can you tell me why this problem happened?

**Comment by bluebill1049** [comment]
We used to support offline mode, service work is cached which needs to be removed.
