### ISSUE TITLE
UseControllerProps typo in docs

### ISSUE THREAD

**Issue by mieumje** [react-hook-form/documentation#960]
**Problem**

It's pretty minor problem.
I think, there is typo in [UseControllerProps documentation](https://react-hook-form.com/ts/#UseControllerProps) about rules utility type definition.

In docs, rules utility type is `Exclude`, but UseControllerProps's rules is `Omit` in [src/types/controllers.ts](https://github.com/react-hook-form/react-hook-form/blob/master/src/types/controller.ts). It's confuse.

**Solution**

I think utility type for rules is `Omit` is correct. If `Omit` is correct, Plz update documentation `Exclude` to `Omit`.

**Comment by Moshyfawn** [comment]
Heya 👋 I've updated the controller types in #959 😉

That said, @bluebill1049, do you think the TS section is still relevant? There're quite a few stale types on that page & I don't think if it makes sense to spend time updating & supporting it. Most of the time, you can go to definition in your IDE of choice & explore the types this way anyway.

**Comment by bluebill1049** [comment]
> Heya 👋 I've updated the controller types in #959 😉
> 
> That said, @bluebill1049, do you think the TS section is still relevant? There're quite a few stale types on that page & I don't think if it makes sense to spend time updating & supporting it. Most of the time, you can go to definition in your IDE of choice & explore the types this way anyway.

Yes, I think we can deprecate that page eventually. The lib always has the updated and correct type.
