### ISSUE TITLE
Website not loading on Firefox

### ISSUE THREAD

**Issue by Raphsuntei** [react-hook-form/documentation#961]
![firefox_vUt585NXwM](https://github.com/react-hook-form/documentation/assets/40801087/e1408246-ef3a-4e2c-8f90-596e1dcd0ca4)

Current version of Firefox, Website is not loading and throwing errors, see screenshot. Works in Chrome, etc.

**Comment by bluebill1049** [comment]
Doing a hard refresh should resolve this issue.

**Comment by Raphsuntei** [comment]
It does, but is that a real solution? It was my first time ever visiting the site, and it wasnt loading. Ideally there is a solution that not other first time visitors only see a black screen.

**Comment by bluebill1049** [comment]
I am sure it's not the first time, it was loading a cached version.
