### ISSUE TITLE
Search results path incorrect

### ISSUE THREAD

**Issue by robations** [react-hook-form/documentation#962]
Every site search result seems to link to a "NOT FOUND" page for me. For example, searching for "rules", the first link is:

https://react-hook-form.com/api/useform/control#rules (not found)

correct link (as far as I know):

https://react-hook-form.com/docs/useform/control#rules

Seems like it’s using Algolia, maybe the index is out of date.

**Comment by bluebill1049** [comment]
fixed.

**Comment by robations** [comment]
Muchos gracias
