### ISSUE TITLE
issue: old documentation links end up in 404

### ISSUE THREAD

**Issue by slax57** [react-hook-form/documentation#971]
### Version Number

N/A

### Codesandbox/Expo snack

N/A

### Steps to reproduce

Navigate to an old documentation link, for instance: https://react-hook-form.com/api/usewatch
The server replies with 404 Not Found

### Expected behaviour

The documentation webpage should be displayed, or at least, a redirection to the correct URL (https://www.react-hook-form.com/api/usewatch in this case) should happen automatically.

I'm not sure if this change in the url was intended or not, but IMO it should be made backwards compatible because otherwise all links to the documentation (stored in StackOverflow, Discord, or other projects documentations) will end up in 404 Error.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aranlucas** [comment]
https://github.com/react-hook-form/documentation/pull/972 might help for this

**Comment by bluebill1049** [comment]
ty @aranlucas
