### ISSUE TITLE
Hover state missing

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/documentation#983]
Looks like the migration has lost the hover effect on API tiles

https://legacy.react-hook-form.com/api

https://legacy.react-hook-form.com/api

![Screenshot 2023-06-26 at 8 45 53 pm](https://github.com/react-hook-form/documentation/assets/10513364/80067e2c-bde6-41ee-b40e-488d032bfdd8)

**Comment by Devanshi-Crypto** [comment]
Hey, can you explain what precisely needs to be done in this issue to me? Maybe I can contribute to the same.

**Comment by bluebill1049** [comment]
thanks @Devanshi-Crypto the previous build has a hover effect https://legacy.react-hook-form.com/api would be good to bring that back. thanks in advance
