### ISSUE TITLE
defaultValues - link to legacy React docs

### ISSUE THREAD

**Issue by Mikilll94** [react-hook-form/documentation#993]
Here we have a link to legacy React docs

https://react-hook-form.com/docs/useform#defaultValues

![Screenshot 2023-07-10 at 13 16 00](https://github.com/react-hook-form/documentation/assets/17653648/19c51c6e-09e2-4a63-ad6f-969bf4d06a64)

This link should point to the currect React docs -> https://react.dev

**Comment by lordvader501** [comment]
I think the link should point to https://react.dev/reference/react-dom/components/input

**Comment by bluebill1049** [comment]
could you like to send a PR?

**Comment by lordvader501** [comment]
> could you like to send a PR?

Ok
