### ISSUE TITLE
defaultValues - broken example

### ISSUE THREAD

**Issue by Mikilll94** [react-hook-form/documentation#994]
This line should be fixed:
```
;<input {...register("hidden")} type="hidden" />
```

![Screenshot 2023-07-10 at 13 18 27](https://github.com/react-hook-form/documentation/assets/17653648/004bb256-91fe-45c3-8d31-a96249b3fca6)

**Comment by fahadsohail482** [comment]
@Mikilll94 I have fixed this in this [RR] (https://github.com/react-hook-form/documentation/pull/997)
Thanks for reporting.
