### ISSUE TITLE
issue: react-hook-form.com doesn't work anymore without www.

### ISSUE THREAD

**Issue by Zerebokep** [react-hook-form/documentation#996]
### Version Number

-

### Codesandbox/Expo snack

-

### Steps to reproduce

title

### Expected behaviour

title

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
it shows a blank page
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
could you try with a hard refresh? seems working fine at my end.

**Comment by Zerebokep** [comment]
Weird, I did that before I wrote the issue, it seems to work fine now, thank you.
